source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'unicorn'
gem 'octokit'
gem 'dotenv-rails'
gem 'rack-cors', require: 'rack/cors'

# Remove these
gem 'uglifier'
gem 'sass-rails'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
end

group :production do
  gem 'rails_12factor'
end
